import esbuild from "esbuild";
import process from "process";
import builtins from "builtin-modules";
import postcss from "postcss";
import tailwindcss from "@tailwindcss/postcss";
import { readFile, writeFile } from "fs/promises";

const banner =
`/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/
(function() {
	// Polyfill 1: import.meta.url
	try {
		if (typeof __filename !== 'undefined' && __filename) {
			var pathToFileURL = require('url').pathToFileURL;
			globalThis.import_meta_url = pathToFileURL(__filename).href;
		} else {
			globalThis.import_meta_url = 'file:///obsidian-plugin/main.js';
		}
	} catch (e) {
		console.error('[import.meta.url polyfill] Error:', e);
		globalThis.import_meta_url = 'file:///obsidian-plugin/main.js';
	}

	// Polyfill 2: events.setMaxListeners with AbortSignal support (Node.js 18+ feature)
	try {
		var events = require('events');
		var originalSetMaxListeners = events.setMaxListeners;
		if (originalSetMaxListeners) {
			events.setMaxListeners = function(n, ...eventTargets) {
				try {
					return originalSetMaxListeners.call(events, n, ...eventTargets);
				} catch (err) {
					// Silently ignore AbortSignal errors in older Node.js versions
					if (err && err.code === 'ERR_INVALID_ARG_TYPE' &&
						err.message && err.message.includes('AbortSignal')) {
						return;
					}
					throw err;
				}
			};
		}
	} catch (e) {
		console.error('[setMaxListeners polyfill] Error:', e);
	}
})();
`;

const prod = (process.argv[2] === "production");

// CSS 빌드 함수 (PostCSS + TailwindCSS v4)
async function buildCSS() {
	try {
		const inputCSS = await readFile('./src/styles/main.css', 'utf8');
		const result = await postcss([
			tailwindcss,
		]).process(inputCSS, {
			from: './src/styles/main.css',
			to: './styles.css',
		});
		await writeFile('./styles.css', result.css);
		console.log('✓ CSS built successfully');
	} catch (error) {
		console.error('✗ CSS build failed:', error.message);
		if (!prod) {
			// 개발 모드에서는 에러를 출력하고 계속 진행
			console.error(error);
		} else {
			throw error;
		}
	}
}

// 초기 CSS 빌드
await buildCSS();

const context = await esbuild.context({
	banner: {
		js: banner,
	},
	entryPoints: ["src/main.ts"],
	bundle: true,
	external: [
		"obsidian",
		"electron",
		"@codemirror/autocomplete",
		"@codemirror/collab",
		"@codemirror/commands",
		"@codemirror/language",
		"@codemirror/lint",
		"@codemirror/search",
		"@codemirror/state",
		"@codemirror/view",
		"@lezer/common",
		"@lezer/highlight",
		"@lezer/lr",
		...builtins],
	format: "cjs",
	define: {
		'import.meta.url': 'globalThis.import_meta_url',
	},
	target: "es2018",
	logLevel: "info",
	sourcemap: prod ? false : "inline",
	treeShaking: true,
	outfile: "main.js",
	minify: prod,
});

if (prod) {
	await context.rebuild();
	process.exit(0);
} else {
	// Watch 모드: CSS 파일 변경 감지
	const chokidar = await import('chokidar');
	const cssWatcher = chokidar.default.watch([
		'./src/styles/**/*.css',
	], {
		ignoreInitial: true,
	});

	cssWatcher.on('change', async (path) => {
		console.log(`\n[CSS] ${path} changed, rebuilding...`);
		await buildCSS();
	});

	// TypeScript 파일 변경 시에도 CSS 재빌드 (Tailwind 클래스 스캔)
	const tsWatcher = chokidar.default.watch('./src/**/*.ts', {
		ignoreInitial: true,
	});

	tsWatcher.on('change', async () => {
		await buildCSS();
	});

	await context.watch();
}
